# -*- coding: utf-8 -*-
"""agrosense_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNUcl1s8eIEIARwSirlB3wkSwFvKWLQn
"""

!pip install shap xgboost scikit-learn tensorflow --quiet

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import os, pickle

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.neighbors import LocalOutlierFactor
from sklearn.linear_model import LinearRegression
from sklearn.cluster import DBSCAN
from sklearn.metrics import (f1_score, precision_score, recall_score,
                             roc_auc_score, classification_report,
                             confusion_matrix, silhouette_score)
from sklearn.model_selection import StratifiedKFold, train_test_split
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
import shap

os.makedirs("models", exist_ok=True)

# ============================================================
# 1. LOAD & CLEAN DATA
# ============================================================
file_path = "/content/drive/MyDrive/agriculture_new/Smart_Farming_Crop_Yield_2024.csv"
df = pd.read_csv(file_path)
df.columns = df.columns.str.strip().str.replace(" ", "_")
df = df.rename(columns={
    'Soil_Moisture_(%)': 'soil_moisture_%',
    'Soil_pH':           'soil_pH',
    'Temperature(C)':    'temperature_C',
    'Rainfall_(mm)':     'rainfall_mm',
    'Humidity_(%)':      'humidity_%',
    'Crop_Type':         'crop_type',
    'Region':            'region'
})

FEATURES = [
    'soil_moisture_%', 'soil_pH', 'temperature_C',
    'rainfall_mm', 'humidity_%', 'NDVI_index'
]
INJECTION_FRACTION = 0.10

# ============================================================
# 2. SEASONAL ENCODING
# ============================================================
df['sowing_date']  = pd.to_datetime(df['sowing_date'], dayfirst=True, errors='coerce')
df['sowing_month'] = df['sowing_date'].dt.month.fillna(6)
df['season_sin']   = np.sin(2 * np.pi * df['sowing_month'] / 12)
df['season_cos']   = np.cos(2 * np.pi * df['sowing_month'] / 12)

# ============================================================
# 3. LABEL ENCODING
# ============================================================
encoders = {}
for col in ['region', 'crop_type']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

# ============================================================
# 4. ANOMALY INJECTION — domain-rule-based, 4 named types
# ============================================================
def inject_contextual_anomalies(df, frac=INJECTION_FRACTION, seed=42):
    np.random.seed(seed)
    df = df.copy()
    df['is_anomaly']  = 0
    df['anomaly_type'] = 'normal'

    for (crop, region), data in df.groupby(['crop_type', 'region']):
        if len(data) < 15:
            continue
        n   = max(1, int(len(data) * frac))
        idx = np.random.choice(data.index, n, replace=False)
        seg = {f: {'low': data[f].quantile(0.10), 'high': data[f].quantile(0.90)}
               for f in FEATURES}

        for i in idx:
            atype = np.random.choice(
                ['drought_stress', 'heat_stress', 'sensor_inconsistency', 'crop_failure'],
                p=[0.25, 0.25, 0.25, 0.25])

            if atype == 'drought_stress':
                df.loc[i, 'soil_moisture_%'] = seg['soil_moisture_%']['low'] * 0.20
                df.loc[i, 'rainfall_mm']      = seg['rainfall_mm']['low']    * 0.30
                df.loc[i, 'NDVI_index']       = seg['NDVI_index']['low']     * 0.40
            elif atype == 'heat_stress':
                df.loc[i, 'temperature_C'] = seg['temperature_C']['high'] * 1.50
                df.loc[i, 'humidity_%']     = seg['humidity_%']['high']    * 1.30
            elif atype == 'sensor_inconsistency':
                df.loc[i, 'rainfall_mm']     = seg['rainfall_mm']['high']
                df.loc[i, 'soil_moisture_%'] = seg['soil_moisture_%']['low'] * 0.20
            elif atype == 'crop_failure':
                df.loc[i, 'NDVI_index']      = seg['NDVI_index']['low']     * 0.30
                df.loc[i, 'soil_moisture_%'] = seg['soil_moisture_%']['low'] * 0.20
                df.loc[i, 'temperature_C']   = seg['temperature_C']['high'] * 1.50

            df.loc[i, 'is_anomaly']   = 1
            df.loc[i, 'anomaly_type'] = atype

    n_anom = df['is_anomaly'].sum()
    print(f"Injected {n_anom} anomalies ({100*n_anom/len(df):.1f}%)")
    print(df['anomaly_type'].value_counts())
    return df

df_eval = inject_contextual_anomalies(df)
print("✅ Anomalies injected\n")

# ============================================================
# 5. TRAIN PER-SEGMENT MODELS
# ============================================================
if_models, lof_models, autoencoders, scalers, fusion_models = {}, {}, {}, {}, {}
segment_stats = {}   # normal range per segment — used by dashboard

for (crop, region), data in df_eval.groupby(['crop_type', 'region']):
    if len(data) < 15:
        continue
    normal_data = data[data['is_anomaly'] == 0]
    X_normal    = normal_data[FEATURES].values

    # Normal range stats saved for dashboard explanation
    segment_stats[(crop, region)] = {
        f: {'low':  normal_data[f].quantile(0.10),
            'high': normal_data[f].quantile(0.90),
            'mean': normal_data[f].mean()}
        for f in FEATURES
    }

    # Isolation Forest
    ifm = IsolationForest(contamination=INJECTION_FRACTION, random_state=42)
    ifm.fit(X_normal)
    if_models[(crop, region)] = ifm

    # LOF
    n_nbrs = min(20, max(5, len(X_normal) - 1))
    lof    = LocalOutlierFactor(n_neighbors=n_nbrs,
                                contamination=INJECTION_FRACTION, novelty=True)
    lof.fit(X_normal)
    lof_models[(crop, region)] = lof

    # Autoencoder 6→8→4→8→6
    scaler   = MinMaxScaler()
    X_scaled = scaler.fit_transform(X_normal)
    scalers[(crop, region)] = scaler

    inp = Input(shape=(X_normal.shape[1],))
    x   = Dense(8, activation='relu')(inp)
    x   = Dense(4, activation='relu')(x)
    x   = Dense(8, activation='relu')(x)
    out = Dense(X_normal.shape[1], activation='sigmoid')(x)
    ae  = Model(inp, out)
    ae.compile(optimizer='adam', loss='mse')
    ae.fit(X_scaled, X_scaled, epochs=20, batch_size=8, verbose=0)
    autoencoders[(crop, region)] = ae

    # Learned sensor fusion — OLS per sensor pair on normal rows
    seg_fusion = {}
    for (xf, yf) in [('rainfall_mm',  'soil_moisture_%'),
                      ('temperature_C','humidity_%'),
                      ('NDVI_index',   'soil_moisture_%')]:
        if len(normal_data) >= 5:
            xv  = normal_data[xf].values.reshape(-1, 1)
            yv  = normal_data[yf].values
            reg = LinearRegression().fit(xv, yv)
            res = yv - reg.predict(xv)
            seg_fusion[(xf, yf)] = {'model': reg, 'std': res.std() + 1e-6}
    fusion_models[(crop, region)] = seg_fusion

print("✅ All segment models trained\n")

# ============================================================
# 6. SCORE FUNCTIONS
# ============================================================
def get_if_score(model, X):
    return float(-model.decision_function(X)[0])

def get_lof_score(model, X):
    return float(-model.decision_function(X)[0])

def get_ae_score(ae, scaler, X):
    Xs    = scaler.transform(X)
    recon = ae.predict(Xs, verbose=0)
    return float(np.mean((Xs - recon) ** 2))

def get_ae_feature_scores(ae, scaler, X):
    Xs    = scaler.transform(X)
    recon = ae.predict(Xs, verbose=0)
    return dict(zip(FEATURES, (Xs - recon)[0] ** 2))

def get_fusion_score(row, key):
    if key not in fusion_models:
        return 0.0, {}
    seg     = fusion_models[key]
    total_z = 0.0
    detail  = {}
    for (xf, yf), info in seg.items():
        expected = info['model'].predict([[row[xf]]])[0]
        residual = abs(row[yf] - expected)
        z        = residual / info['std']
        total_z += z
        detail[f"{xf}→{yf}"] = round(z, 3)
    return total_z / max(len(seg), 1), detail

# ============================================================
# 7. GLOBAL NORMALISATION
# ============================================================
all_if, all_lof, all_ae, all_fus = [], [], [], []

for _, row in df_eval.iterrows():
    key = (row['crop_type'], row['region'])
    if key not in if_models:
        continue
    X = np.array([row[FEATURES]])
    all_if.append(get_if_score(if_models[key], X))
    all_lof.append(get_lof_score(lof_models[key], X))
    all_ae.append(get_ae_score(autoencoders[key], scalers[key], X))
    fs, _ = get_fusion_score(row, key)
    all_fus.append(fs)

norm_if  = MinMaxScaler().fit(np.array(all_if).reshape(-1, 1))
norm_lof = MinMaxScaler().fit(np.array(all_lof).reshape(-1, 1))
norm_ae  = MinMaxScaler().fit(np.array(all_ae).reshape(-1, 1))
norm_fus = MinMaxScaler().fit(np.array(all_fus).reshape(-1, 1))
ae_threshold_raw = np.percentile(all_ae, 95)

# ============================================================
# 8. F1-BASED ENSEMBLE WEIGHTS
# ============================================================
y_true_list, p_if, p_lof, p_ae, p_fus = [], [], [], [], []

for _, row in df_eval.iterrows():
    key = (row['crop_type'], row['region'])
    if key not in if_models:
        continue
    X = np.array([row[FEATURES]])
    y_true_list.append(row['is_anomaly'])
    p_if.append(1 if if_models[key].predict(X)[0] == -1 else 0)
    p_lof.append(1 if lof_models[key].predict(X)[0] == -1 else 0)
    p_ae.append(1 if get_ae_score(autoencoders[key], scalers[key], X) > ae_threshold_raw else 0)
    fs, _ = get_fusion_score(row, key)
    p_fus.append(1 if fs > 2.0 else 0)

y_true_arr = np.array(y_true_list)
f1s = {
    'if':     f1_score(y_true_arr, p_if,  zero_division=0),
    'lof':    f1_score(y_true_arr, p_lof, zero_division=0),
    'ae':     f1_score(y_true_arr, p_ae,  zero_division=0),
    'fusion': f1_score(y_true_arr, p_fus, zero_division=0),
}
total_f1 = sum(f1s.values()) + 1e-9
weights  = {k: v / total_f1 for k, v in f1s.items()}

print("Per-model F1 & weights:")
for k, v in f1s.items():
    print(f"  {k:8s}: F1={v:.3f}  weight={weights[k]:.3f}")
print()

# ============================================================
# 9. FINAL ENSEMBLE SCORE
# ============================================================
def compute_final_score(row):
    key = (row['crop_type'], row['region'])
    if key not in if_models:
        return None
    X    = np.array([row[FEATURES]])
    if_s = float(norm_if.transform([[get_if_score(if_models[key], X)]])[0][0])
    lf_s = float(norm_lof.transform([[get_lof_score(lof_models[key], X)]])[0][0])
    ae_s = float(norm_ae.transform([[get_ae_score(autoencoders[key], scalers[key], X)]])[0][0])
    fs, _ = get_fusion_score(row, key)
    fu_s = float(norm_fus.transform([[fs]])[0][0])
    return (weights['if']     * if_s +
            weights['lof']    * lf_s +
            weights['ae']     * ae_s +
            weights['fusion'] * fu_s)

df_eval['final_score'] = df_eval.apply(compute_final_score, axis=1)
df_eval = df_eval.dropna(subset=['final_score']).copy()

# ============================================================
# 10. THRESHOLD OPTIMISATION
# ============================================================
best_thresh, best_f1_val = 0, 0
for t in np.linspace(0, 1, 200):
    pred = (df_eval['final_score'] > t).astype(int)
    f1   = f1_score(df_eval['is_anomaly'], pred, zero_division=0)
    if f1 > best_f1_val:
        best_f1_val = f1
        best_thresh = t

df_eval['predicted_anomaly'] = (df_eval['final_score'] > best_thresh).astype(int)
print(f"Optimised threshold: {best_thresh:.3f}  |  Best F1: {best_f1_val:.3f}\n")

# ============================================================
# 11. FULL ABLATION STUDY — 6-model comparison
# ============================================================
print("=" * 60)
print("FULL ABLATION STUDY")
print("=" * 60)

def row_metrics(name, y_true, y_pred, y_score=None):
    auc = roc_auc_score(y_true, y_score) if (y_score is not None and
          len(np.unique(y_true)) > 1) else float('nan')
    return {
        'Model':     name,
        'F1':        round(f1_score(y_true, y_pred, zero_division=0), 3),
        'Precision': round(precision_score(y_true, y_pred, zero_division=0), 3),
        'Recall':    round(recall_score(y_true, y_pred, zero_division=0), 3),
        'AUC-ROC':   round(auc, 3),
    }

y_all  = df_eval['is_anomaly'].values
X_all  = df_eval[FEATURES].values

# Global IF baseline
global_if = IsolationForest(contamination=INJECTION_FRACTION, random_state=42)
global_if.fit(X_all[y_all == 0])
global_pred  = (global_if.predict(X_all) == -1).astype(int)
global_score = -global_if.decision_function(X_all)
global_score_n = (global_score - global_score.min()) / (global_score.max() - global_score.min() + 1e-9)

# Per-row segmented predictions (recompute on df_eval rows)
sp_if, sp_lof, sp_ae, sp_fus = [], [], [], []
sc_if, sc_lof, sc_ae, sc_fus, sc_ens = [], [], [], [], []

for _, row in df_eval.iterrows():
    key = (row['crop_type'], row['region'])
    X   = np.array([row[FEATURES]])
    if_r  = get_if_score(if_models[key], X)
    lof_r = get_lof_score(lof_models[key], X)
    ae_r  = get_ae_score(autoencoders[key], scalers[key], X)
    fs_r, _ = get_fusion_score(row, key)

    if_n  = float(norm_if.transform([[if_r]])[0][0])
    lof_n = float(norm_lof.transform([[lof_r]])[0][0])
    ae_n  = float(norm_ae.transform([[ae_r]])[0][0])
    fus_n = float(norm_fus.transform([[fs_r]])[0][0])

    sp_if.append(1 if if_models[key].predict(X)[0] == -1 else 0)
    sp_lof.append(1 if lof_models[key].predict(X)[0] == -1 else 0)
    sp_ae.append(1 if ae_r > ae_threshold_raw else 0)
    sp_fus.append(1 if fs_r > 2.0 else 0)

    sc_if.append(if_n);  sc_lof.append(lof_n)
    sc_ae.append(ae_n);  sc_fus.append(fus_n)
    sc_ens.append(row['final_score'])

comp_rows = [
    row_metrics("1. Global IF (no context — baseline)", y_all, global_pred, global_score_n),
    row_metrics("2. Segmented IF only",      y_all, sp_if,  sc_if),
    row_metrics("3. Segmented LOF only",     y_all, sp_lof, sc_lof),
    row_metrics("4. Segmented AE only",      y_all, sp_ae,  sc_ae),
    row_metrics("5. Segmented Fusion only",  y_all, sp_fus, sc_fus),
    row_metrics("6. Proposed Ensemble (ours)", y_all, df_eval['predicted_anomaly'].values, sc_ens),
]
comp_df = pd.DataFrame(comp_rows).set_index('Model')
print(comp_df.to_string())
print()

# ============================================================
# 12. 5-FOLD CROSS-VALIDATION
# ============================================================
print("=" * 60)
print("5-FOLD STRATIFIED CROSS-VALIDATION")
print("=" * 60)

skf        = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_f1_ens  = []
cv_f1_glob = []
X_cv = df_eval[FEATURES].values
y_cv = df_eval['is_anomaly'].values

for fold, (train_idx, val_idx) in enumerate(skf.split(X_cv, y_cv)):
    Xtr, ytr = X_cv[train_idx], y_cv[train_idx]
    Xvl, yvl = X_cv[val_idx],   y_cv[val_idx]

    gf = IsolationForest(contamination=INJECTION_FRACTION, random_state=42)
    gf.fit(Xtr[ytr == 0])
    gp = (gf.predict(Xvl) == -1).astype(int)
    cv_f1_glob.append(f1_score(yvl, gp, zero_division=0))

    fold_preds = (df_eval.iloc[val_idx]['final_score'] > best_thresh).astype(int)
    cv_f1_ens.append(f1_score(yvl, fold_preds, zero_division=0))

print(f"Global IF — F1: {np.mean(cv_f1_glob):.3f} ± {np.std(cv_f1_glob):.3f}")
print(f"Ensemble  — F1: {np.mean(cv_f1_ens):.3f} ± {np.std(cv_f1_ens):.3f}\n")

# ============================================================
# 13. PER-SEGMENT EVALUATION
# ============================================================
print("=" * 60)
print("PER-SEGMENT EVALUATION")
print("=" * 60)

seg_rows = []
for (crop, region), grp in df_eval.groupby(['crop_type', 'region']):
    if grp['is_anomaly'].sum() == 0:
        continue
    cn = encoders['crop_type'].inverse_transform([crop])[0]
    rn = encoders['region'].inverse_transform([region])[0]
    seg_rows.append({
        'Crop': cn, 'Region': rn, 'N': len(grp),
        'Anomalies': int(grp['is_anomaly'].sum()),
        'F1':        round(f1_score(grp['is_anomaly'], grp['predicted_anomaly'], zero_division=0), 3),
        'Precision': round(precision_score(grp['is_anomaly'], grp['predicted_anomaly'], zero_division=0), 3),
        'Recall':    round(recall_score(grp['is_anomaly'], grp['predicted_anomaly'], zero_division=0), 3),
    })
seg_df = pd.DataFrame(seg_rows).sort_values('F1', ascending=False)
print(seg_df.to_string(index=False))
print()

# ============================================================
# 14. SHAP EXPLAINABILITY
# ============================================================
print("=" * 60)
print("SHAP EXPLAINABILITY")
print("=" * 60)

key_demo    = max(if_models.keys(),
                  key=lambda k: len(df_eval[(df_eval['crop_type']==k[0]) &
                                            (df_eval['region']==k[1])]))
X_demo      = df_eval[(df_eval['crop_type']==key_demo[0]) &
                       (df_eval['region']==key_demo[1])][FEATURES].values
crop_demo   = encoders['crop_type'].inverse_transform([key_demo[0]])[0]
region_demo = encoders['region'].inverse_transform([key_demo[1]])[0]

explainer_if   = shap.TreeExplainer(if_models[key_demo])
shap_values_if = explainer_if.shap_values(X_demo)
print(f"Segment: {crop_demo} / {region_demo}  ({len(X_demo)} rows)")
shap.summary_plot(shap_values_if, X_demo, feature_names=FEATURES,
                  plot_type='bar', show=False)
plt.title(f"SHAP — Isolation Forest | {crop_demo} / {region_demo}")
plt.tight_layout(); plt.savefig('shap_if_summary.png', dpi=150); plt.close()
print("Saved: shap_if_summary.png\n")

# ============================================================
# 15. ABLATION FIGURE — publication quality
# ============================================================
fig = plt.figure(figsize=(18, 12))
gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)

model_labels = ['Global IF\n(no context)', 'Seg. IF', 'Seg. LOF',
                'Seg. AE', 'Seg. Fusion', 'Ensemble\n(proposed)']
bar_colors   = ['#888780','#9FE1CB','#5DCAA5','#1D9E75','#0F6E56','#378ADD']
edge_colors  = ['none','none','none','none','none','#042C53']
panel_labels = ['A','B','C','D']
metrics_plot = ['F1','Precision','Recall','AUC-ROC']
panels       = [(0,0),(0,1),(1,0),(1,1)]

baseline_vals = {m: comp_df.loc['1. Global IF (no context — baseline)', m]
                 for m in metrics_plot}

for idx, ((r, c), metric) in enumerate(zip(panels, metrics_plot)):
    ax   = fig.add_subplot(gs[r, c])
    vals = [comp_df.loc[m, metric] for m in comp_df.index]
    bars = ax.bar(model_labels, vals, color=bar_colors,
                  edgecolor=edge_colors, linewidth=1.8)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.012,
                f'{val:.3f}', ha='center', va='bottom', fontsize=9,
                fontweight='bold' if val == max(vals) else 'normal')
    ax.axhline(baseline_vals[metric], linestyle='--', color='#888780',
               linewidth=1.2, alpha=0.8)
    ax.set_ylim(0, 1.18); ax.set_ylabel(metric, fontsize=12)
    ax.set_title(metric, fontsize=13, pad=10)
    ax.tick_params(axis='x', labelsize=9)
    ax.text(-0.12, 1.05, panel_labels[idx], transform=ax.transAxes,
            fontsize=15, fontweight='bold')

legend_elements = [
    Patch(facecolor='#888780', label='Global IF (no segmentation)'),
    Patch(facecolor='#9FE1CB', label='Segmented IF'),
    Patch(facecolor='#5DCAA5', label='Segmented LOF'),
    Patch(facecolor='#1D9E75', label='Segmented AE'),
    Patch(facecolor='#0F6E56', label='Segmented Fusion'),
    Patch(facecolor='#378ADD', edgecolor='#042C53', linewidth=1.5,
          label='Proposed Ensemble (ours)'),
]
fig.legend(handles=legend_elements, loc='upper center', ncol=3, fontsize=10,
           bbox_to_anchor=(0.5, 1.04), frameon=True, edgecolor='#cccccc')
plt.savefig('ablation_full_final.png', dpi=300, bbox_inches='tight')
plt.close()
print("Saved: ablation_full_final.png\n")

# ============================================================
# 16. RESULTS SUMMARY FIGURE (4-panel)
# ============================================================
fig = plt.figure(figsize=(16, 12))
gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.35)

ax1 = fig.add_subplot(gs[0, 0])
metrics_names = ['F1', 'Precision', 'Recall']
global_vals   = [comp_df.loc['1. Global IF (no context — baseline)', m] for m in metrics_names]
ens_vals      = [comp_df.loc['6. Proposed Ensemble (ours)', m] for m in metrics_names]
x = np.arange(3)
bars1 = ax1.bar(x - 0.2, global_vals, 0.35, label='Global IF', color='#888780')
bars2 = ax1.bar(x + 0.2, ens_vals,    0.35, label='Ensemble',  color='#378ADD')
ax1.set_xticks(x); ax1.set_xticklabels(metrics_names)
ax1.set_ylim(0, 1.1); ax1.set_ylabel('Score')
ax1.set_title('A. Ablation: Global vs Context-Segmented', fontsize=11)
ax1.legend(fontsize=9)
for bar in list(bars1) + list(bars2):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
             f'{bar.get_height():.2f}', ha='center', fontsize=8)

ax2 = fig.add_subplot(gs[0, 1])
ax2.hist(df_eval[df_eval['is_anomaly']==0]['final_score'], bins=30,
         alpha=0.7, label='Normal',  color='#639922')
ax2.hist(df_eval[df_eval['is_anomaly']==1]['final_score'], bins=30,
         alpha=0.7, label='Anomaly', color='#E24B4A')
ax2.axvline(best_thresh, color='black', linestyle='--', linewidth=1.5,
            label=f'Threshold={best_thresh:.2f}')
ax2.set_xlabel('Final Ensemble Score'); ax2.set_ylabel('Count')
ax2.set_title('B. Score Distribution', fontsize=11); ax2.legend(fontsize=9)

ax3 = fig.add_subplot(gs[1, 0])
pivot = seg_df.pivot_table(index='Crop', columns='Region', values='F1')
im    = ax3.imshow(pivot.values, cmap='RdYlGn', vmin=0, vmax=1, aspect='auto')
ax3.set_xticks(range(len(pivot.columns)))
ax3.set_xticklabels(pivot.columns, rotation=30, fontsize=8)
ax3.set_yticks(range(len(pivot.index)))
ax3.set_yticklabels(pivot.index, fontsize=8)
for i in range(len(pivot.index)):
    for j in range(len(pivot.columns)):
        val = pivot.values[i, j]
        if not np.isnan(val):
            ax3.text(j, i, f'{val:.2f}', ha='center', va='center', fontsize=8,
                     color='white' if val < 0.5 else 'black')
plt.colorbar(im, ax=ax3)
ax3.set_title('C. Per-Segment F1 Score', fontsize=11)

ax4 = fig.add_subplot(gs[1, 1])
folds = list(range(1, 6))
ax4.plot(folds, cv_f1_glob, 'o--', color='#888780',
         label=f'Global IF μ={np.mean(cv_f1_glob):.3f}')
ax4.plot(folds, cv_f1_ens,  's-',  color='#378ADD',
         label=f'Ensemble  μ={np.mean(cv_f1_ens):.3f}')
ax4.axhline(np.mean(cv_f1_ens),  linestyle=':', color='#378ADD', alpha=0.5)
ax4.axhline(np.mean(cv_f1_glob), linestyle=':', color='#888780', alpha=0.5)
ax4.set_xlabel('Fold'); ax4.set_ylabel('F1 Score')
ax4.set_title('D. 5-Fold Cross-Validation', fontsize=11)
ax4.set_ylim(0, 1.1); ax4.legend(fontsize=9)

plt.suptitle('Hybrid Contextual Anomaly Detection — Results Summary',
             fontsize=13, y=1.01)
plt.savefig('results_summary.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: results_summary.png\n")

# ============================================================
# 17. [GEO] GEOSPATIAL CLUSTERING — NEW CONTRIBUTION
#
# Purpose: reveal whether anomalies cluster spatially
# (local drought, regional heatwave) or are distributed
# uniformly. Uses DBSCAN on lat/lon + ensemble score.
# ============================================================
print("=" * 60)
print("[GEO] GEOSPATIAL CLUSTERING ANALYSIS")
print("=" * 60)

# Merge lat/lon back from original df using index
# (df_eval rows correspond to df rows — same index)
df_eval['latitude']  = df.loc[df_eval.index, 'latitude'].values
df_eval['longitude'] = df.loc[df_eval.index, 'longitude'].values

# --- DBSCAN on (lat, lon) ---
# eps ~1.5 degrees ≈ ~150 km radius; min_samples=3
coords       = df_eval[['latitude', 'longitude']].values
coords_norm  = MinMaxScaler().fit_transform(coords)
db           = DBSCAN(eps=0.08, min_samples=3).fit(coords_norm)
df_eval['geo_cluster'] = db.labels_   # -1 = noise (isolated farms)

n_clusters = len(set(db.labels_)) - (1 if -1 in db.labels_ else 0)
print(f"DBSCAN found {n_clusters} geographic clusters")
print(f"Noise points (isolated): {(db.labels_ == -1).sum()}\n")

# --- Anomaly rate per geographic cluster ---
cluster_summary = []
for cid in sorted(df_eval['geo_cluster'].unique()):
    grp = df_eval[df_eval['geo_cluster'] == cid]
    anom_rate = grp['is_anomaly'].mean()
    avg_score = grp['final_score'].mean()
    label     = f"Cluster {cid}" if cid != -1 else "Isolated"
    cluster_summary.append({
        'Cluster':    label,
        'Farms':      len(grp),
        'Anomaly %':  round(anom_rate * 100, 1),
        'Avg Score':  round(avg_score, 3),
        'Lat centre': round(grp['latitude'].mean(), 2),
        'Lon centre': round(grp['longitude'].mean(), 2),
    })

cluster_df = pd.DataFrame(cluster_summary)
print(cluster_df.to_string(index=False))
print()

# --- Spatial anomaly interpretation ---
high_anom_clusters = cluster_df[cluster_df['Anomaly %'] > 15]
if len(high_anom_clusters) > 0:
    print("High-anomaly clusters (>15% rate) — possible localised stress events:")
    print(high_anom_clusters[['Cluster','Anomaly %','Lat centre','Lon centre']].to_string(index=False))
else:
    print("Anomalies are spatially distributed — no localised hotspot detected.")
print()

# --- Geospatial visualisation ---
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Panel 1: Anomaly scatter map
ax = axes[0]
normal_pts = df_eval[df_eval['is_anomaly'] == 0]
anom_pts   = df_eval[df_eval['is_anomaly'] == 1]
ax.scatter(normal_pts['longitude'], normal_pts['latitude'],
           c='#1D9E75', alpha=0.5, s=30, label='Normal', zorder=2)
ax.scatter(anom_pts['longitude'], anom_pts['latitude'],
           c='#E24B4A', alpha=0.8, s=60, marker='X', label='Anomaly', zorder=3)
ax.set_xlabel('Longitude'); ax.set_ylabel('Latitude')
ax.set_title('A. Spatial Distribution of Anomalies', fontsize=12)
ax.legend(fontsize=10); ax.grid(True, alpha=0.3)

# Panel 2: DBSCAN cluster map coloured by anomaly rate
ax2 = axes[1]
cmap = plt.cm.RdYlGn_r
for cid in sorted(df_eval['geo_cluster'].unique()):
    grp = df_eval[df_eval['geo_cluster'] == cid]
    rate   = grp['is_anomaly'].mean()
    colour = cmap(rate)
    marker = 'o' if cid != -1 else 'x'
    label  = f"Cluster {cid} ({rate*100:.0f}%)" if cid != -1 else "Isolated"
    ax2.scatter(grp['longitude'], grp['latitude'],
                c=[colour]*len(grp), s=50, marker=marker,
                alpha=0.8, label=label, zorder=2)

sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(0, 1))
sm.set_array([])
plt.colorbar(sm, ax=ax2, label='Anomaly rate (0=low, 1=high)')
ax2.set_xlabel('Longitude'); ax2.set_ylabel('Latitude')
ax2.set_title('B. Geographic Clusters — Anomaly Rate', fontsize=12)
ax2.grid(True, alpha=0.3)

plt.suptitle('Geospatial Anomaly Clustering Analysis', fontsize=13)
plt.tight_layout()
plt.savefig('geospatial_clustering.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: geospatial_clustering.png\n")

# --- Spatial autocorrelation test (Moran-like) ---
# Check if anomalies cluster more than random using a simple permutation test
observed_mean_dist = []
for idx, row in df_eval[df_eval['is_anomaly']==1].iterrows():
    dists = np.sqrt((df_eval[df_eval['is_anomaly']==1]['latitude']  - row['latitude'])**2 +
                    (df_eval[df_eval['is_anomaly']==1]['longitude'] - row['longitude'])**2)
    dists = dists[dists > 0]
    if len(dists) > 0:
        observed_mean_dist.append(dists.min())

null_dists = []
for _ in range(500):
    sample = df_eval.sample(int(df_eval['is_anomaly'].sum()), random_state=None)
    d = []
    for idx, row in sample.iterrows():
        dists = np.sqrt((sample['latitude']  - row['latitude'])**2 +
                        (sample['longitude'] - row['longitude'])**2)
        dists = dists[dists > 0]
        if len(dists) > 0:
            d.append(dists.min())
    null_dists.append(np.mean(d) if d else 0)

obs_mean  = np.mean(observed_mean_dist)
null_mean = np.mean(null_dists)
p_value   = np.mean(np.array(null_dists) <= obs_mean)

print(f"Spatial clustering test:")
print(f"  Observed mean nearest-neighbour dist: {obs_mean:.4f}°")
print(f"  Null distribution mean:               {null_mean:.4f}°")
print(f"  p-value: {p_value:.3f} "
      f"({'clustered — anomalies not random' if p_value < 0.05 else 'no significant spatial clustering'})\n")

# ============================================================
# 18. [CLS] ANOMALY TYPE CLASSIFICATION — NEW CONTRIBUTION
#
# Purpose: not just binary detection but diagnosis.
# Trains a Random Forest on the 4 model scores + feature
# values to classify anomaly type: drought_stress,
# heat_stress, sensor_inconsistency, crop_failure.
# Only trains on anomalous rows — normal rows excluded.
# ============================================================
print("=" * 60)
print("[CLS] ANOMALY TYPE CLASSIFICATION")
print("=" * 60)

# Build feature matrix for classifier
# Inputs: 4 ensemble scores + 6 sensor features = 10 features
classifier_feature_names = (
    ['score_if', 'score_lof', 'score_ae', 'score_fusion'] + FEATURES
)

cls_rows = []
for _, row in df_eval.iterrows():
    key = (row['crop_type'], row['region'])
    if key not in if_models:
        continue
    X = np.array([row[FEATURES]])

    if_n  = float(norm_if.transform([[get_if_score(if_models[key], X)]])[0][0])
    lof_n = float(norm_lof.transform([[get_lof_score(lof_models[key], X)]])[0][0])
    ae_n  = float(norm_ae.transform([[get_ae_score(autoencoders[key], scalers[key], X)]])[0][0])
    fs, _ = get_fusion_score(row, key)
    fus_n = float(norm_fus.transform([[fs]])[0][0])

    cls_rows.append([if_n, lof_n, ae_n, fus_n] +
                    [row[f] for f in FEATURES] +
                    [row['anomaly_type']])

cls_df = pd.DataFrame(cls_rows,
                      columns=classifier_feature_names + ['anomaly_type'])

# Train only on anomalous rows (4 classes: the named types)
anomaly_only = cls_df[cls_df['anomaly_type'] != 'normal'].copy()

TYPE_LABELS = ['drought_stress', 'heat_stress',
               'sensor_inconsistency', 'crop_failure']

print(f"Anomalous rows available for classifier: {len(anomaly_only)}")
print(anomaly_only['anomaly_type'].value_counts())
print()

X_cls = anomaly_only[classifier_feature_names].values
y_cls = anomaly_only['anomaly_type'].values

X_cls_tr, X_cls_te, y_cls_tr, y_cls_te = train_test_split(
    X_cls, y_cls, test_size=0.25, random_state=42, stratify=y_cls)

# Random Forest classifier
type_classifier = RandomForestClassifier(
    n_estimators=200, max_depth=8, random_state=42, class_weight='balanced')
type_classifier.fit(X_cls_tr, y_cls_tr)

y_cls_pred = type_classifier.predict(X_cls_te)
cls_acc    = (y_cls_pred == y_cls_te).mean()

print(f"Classification Accuracy: {cls_acc:.3f}")
print()
print("Classification Report:")
print(classification_report(y_cls_te, y_cls_pred,
                             target_names=TYPE_LABELS, zero_division=0))

# Confusion matrix
cm = confusion_matrix(y_cls_te, y_cls_pred, labels=TYPE_LABELS)
fig, ax = plt.subplots(figsize=(7, 6))
im = ax.imshow(cm, cmap='Blues')
ax.set_xticks(range(4)); ax.set_yticks(range(4))
ax.set_xticklabels([l.replace('_',' ') for l in TYPE_LABELS], rotation=30, fontsize=9)
ax.set_yticklabels([l.replace('_',' ') for l in TYPE_LABELS], fontsize=9)
ax.set_xlabel('Predicted'); ax.set_ylabel('Actual')
ax.set_title('Anomaly Type Classification — Confusion Matrix', fontsize=12)
for i in range(4):
    for j in range(4):
        ax.text(j, i, str(cm[i,j]), ha='center', va='center', fontsize=12,
                fontweight='bold',
                color='white' if cm[i,j] > cm.max()/2 else 'black')
plt.colorbar(im, ax=ax)
plt.tight_layout()
plt.savefig('anomaly_type_classification.png', dpi=150)
plt.close()
print("Saved: anomaly_type_classification.png\n")

# SHAP for classifier feature importance
print("Computing SHAP for anomaly type classifier...")
cls_explainer  = shap.TreeExplainer(type_classifier)
shap_cls_vals  = cls_explainer.shap_values(X_cls_te)

# shap_vals is list of arrays (one per class) — sum abs across classes
shap_importance = np.abs(np.array(shap_cls_vals)).mean(axis=0).mean(axis=0)
shap_feat_df    = pd.DataFrame({
    'Feature': classifier_feature_names,
    'SHAP Importance': shap_importance
}).sort_values('SHAP Importance', ascending=False)

print("Top features for anomaly type diagnosis:")
print(shap_feat_df.to_string(index=False))

plt.figure(figsize=(9, 5))
plt.barh(shap_feat_df['Feature'][::-1], shap_feat_df['SHAP Importance'][::-1],
         color='#378ADD')
plt.xlabel('Mean |SHAP| value')
plt.title('Anomaly Type Classifier — Feature Importance (SHAP)')
plt.tight_layout()
plt.savefig('shap_type_classifier.png', dpi=150)
plt.close()
print("Saved: shap_type_classifier.png\n")

# ============================================================
# 19. YIELD MODEL — Agronomic formula
# ============================================================
print("=" * 60)
print("YIELD PREDICTION — Agronomic Formula Model")
print("=" * 60)

_base_yields = {
    'Cotton': 3800, 'Maize': 5500, 'Rice': 4500,
    'Soybean': 3200, 'Wheat': 4800
}
crop_base_map = {}
for name in encoders['crop_type'].classes_:
    enc = int(encoders['crop_type'].transform([name])[0])
    crop_base_map[enc] = _base_yields.get(name, 4000)

def formula_yield(user_dict, crop_enc):
    base = crop_base_map.get(int(crop_enc), 4000)
    sm   = user_dict.get('soil_moisture_%', 25)
    tmp  = user_dict.get('temperature_C', 24)
    ph   = user_dict.get('soil_pH', 6.5)
    ndvi = user_dict.get('NDVI_index', 0.6)
    rain = user_dict.get('rainfall_mm', 180)
    sun  = user_dict.get('sunlight_hours', 7)
    pest = user_dict.get('pesticide_usage_ml', 25)

    sm_f  = 1.0 if 20<=sm<=35 else (max(0.40, 0.60+0.02*sm) if sm<20
            else max(0.65, 1.0-0.012*(sm-35)))
    tmp_f = 1.0 if 20<=tmp<=30 else (max(0.65, 0.65+0.017*(tmp-10)) if tmp<20
            else max(0.45, 1.0-0.028*(tmp-30)))
    ph_f  = 1.0 if 6.0<=ph<=7.0 else max(0.70, 1.0-0.12*abs(ph-6.5))
    ndvi_f= max(0.30, min(1.30, 0.50+0.80*ndvi))
    rain_f= 1.0 if 100<=rain<=250 else (max(0.50, 0.50+0.005*rain) if rain<100
            else max(0.70, 1.0-0.0012*(rain-250)))
    sun_f = min(1.15, max(0.70, 0.70+0.045*sun))
    pest_f= 1.0 if 15<=pest<=35 else max(0.80, 1.0-0.006*abs(pest-25))

    return max(300.0, round(
        base * sm_f * tmp_f * ph_f * ndvi_f * rain_f * sun_f * pest_f, 0))

print("Yield formula verification (default inputs):")
test = {'soil_moisture_%':25,'soil_pH':6.5,'temperature_C':24,'rainfall_mm':180,
        'humidity_%':65,'NDVI_index':0.6,'sunlight_hours':7,'pesticide_usage_ml':25}
for enc, base in crop_base_map.items():
    name = encoders['crop_type'].inverse_transform([enc])[0]
    print(f"  {name}: {formula_yield(test, enc):.0f} kg/ha")
print()

# ============================================================
# 20. PREDICT FUNCTION — full report with type classification
# ============================================================
def predict_user_input(user_data):
    # Encode
    crop_enc   = (encoders['crop_type'].transform([user_data['crop_type']])[0]
                  if user_data['crop_type'] in encoders['crop_type'].classes_ else None)
    region_enc = (encoders['region'].transform([user_data['region']])[0]
                  if user_data['region'] in encoders['region'].classes_ else None)

    if crop_enc is None or region_enc is None:
        print("Invalid crop or region.")
        return
    key = (crop_enc, region_enc)
    if key not in if_models:
        print("No model for this crop-region combination.")
        return

    X = np.array([[user_data[f] for f in FEATURES]])

    if_r   = get_if_score(if_models[key], X)
    lof_r  = get_lof_score(lof_models[key], X)
    ae_r   = get_ae_score(autoencoders[key], scalers[key], X)
    fs_r, fusion_detail = get_fusion_score(user_data, key)

    if_s  = float(norm_if.transform([[if_r]])[0][0])
    lof_s = float(norm_lof.transform([[lof_r]])[0][0])
    ae_s  = float(norm_ae.transform([[ae_r]])[0][0])
    fus_s = float(norm_fus.transform([[fs_r]])[0][0])

    final_score = (weights['if']     * if_s  +
                   weights['lof']    * lof_s +
                   weights['ae']     * ae_s  +
                   weights['fusion'] * fus_s)

    print("\n" + "=" * 55)
    print(f"  ANOMALY DETECTION REPORT")
    print(f"  Crop: {user_data['crop_type']}  |  Region: {user_data['region']}")
    print("=" * 55)

    print(f"\nModel Scores (normalised 0-1):")
    print(f"  IF:     {if_s:.3f}  (weight: {weights['if']:.3f})")
    print(f"  LOF:    {lof_s:.3f}  (weight: {weights['lof']:.3f})")
    print(f"  AE:     {ae_s:.3f}  (weight: {weights['ae']:.3f})")
    print(f"  Fusion: {fus_s:.3f}  (weight: {weights['fusion']:.3f})")
    print(f"\nFinal Ensemble Score: {final_score:.3f}  |  Threshold: {best_thresh:.3f}")

    tendency_low = best_thresh - 0.05
    if final_score > best_thresh:
        print("\n  ⚠  ANOMALY DETECTED")
    elif final_score >= tendency_low:
        print("\n  🔮  TENDENCY TOWARDS ANOMALY — monitor closely")
    elif final_score >= 0.5:
        print("\n  ⚡  BORDERLINE CONDITIONS")
    else:
        print("\n  ✓  CONDITIONS NORMAL")

    # Parameter range issues
    if key in segment_stats:
        seg_s = segment_stats[key]
        issues = []
        for f in FEATURES:
            if f not in seg_s: continue
            val = user_data[f]
            low, high = seg_s[f]['low'], seg_s[f]['high']
            if   val < low:  issues.append(f"  {f}: {val:.2f} too LOW  (normal > {low:.2f})")
            elif val > high: issues.append(f"  {f}: {val:.2f} too HIGH (normal < {high:.2f})")
        if issues:
            print("\nParameter Issues:")
            for i in issues: print(i)

    # SHAP explanation
    exp = shap.TreeExplainer(if_models[key])
    sv  = exp.shap_values(X)[0]
    print("\nSHAP Feature Contributions (Isolation Forest):")
    for feat, val in sorted(zip(FEATURES, sv), key=lambda x: abs(x[1]), reverse=True):
        direction = "→ ANOMALY" if val > 0 else "→ NORMAL"
        print(f"  {feat:22s}: {val:+.4f}  {direction}")

    # AE feature reconstruction
    ae_feat  = get_ae_feature_scores(autoencoders[key], scalers[key], X)
    top_ae   = sorted(ae_feat.items(), key=lambda x: x[1], reverse=True)
    print("\nAutoencoder — Top Anomalous Features:")
    for feat, err in top_ae[:3]:
        print(f"  {feat:22s}: reconstruction error = {err:.5f}")

    # Sensor fusion z-scores
    if fusion_detail:
        print("\nSensor Fusion — Learned Relationship Deviations:")
        for pair, z in fusion_detail.items():
            flag = " ← SUSPICIOUS" if z > 2.0 else ""
            print(f"  {pair:35s}: z-score = {z:.2f}{flag}")

    # [CLS] Anomaly type diagnosis
    if final_score > best_thresh:
        cls_input = np.array([[if_s, lof_s, ae_s, fus_s] +
                               [user_data[f] for f in FEATURES]])
        cls_pred  = type_classifier.predict(cls_input)[0]
        cls_proba = type_classifier.predict_proba(cls_input)[0]
        cls_classes = type_classifier.classes_
        print(f"\n[DIAGNOSIS] Probable anomaly type: {cls_pred.upper().replace('_',' ')}")
        print("  Probability breakdown:")
        for cls, prob in sorted(zip(cls_classes, cls_proba),
                                key=lambda x: x[1], reverse=True):
            bar = '█' * int(prob * 20)
            print(f"    {cls:25s}: {prob:.3f}  {bar}")

    # Geospatial context
    lat = user_data.get('latitude', None)
    lon = user_data.get('longitude', None)
    if lat is not None and lon is not None:
        lat_n = (lat - df_eval['latitude'].min()) / (df_eval['latitude'].max() - df_eval['latitude'].min() + 1e-9)
        lon_n = (lon - df_eval['longitude'].min()) / (df_eval['longitude'].max() - df_eval['longitude'].min() + 1e-9)
        # Assign to nearest cluster centroid
        nearby = df_eval[
            (abs(df_eval['latitude'] - lat) < 2.0) &
            (abs(df_eval['longitude'] - lon) < 2.0)
        ]
        if len(nearby) > 0:
            local_anom_rate = nearby['is_anomaly'].mean()
            print(f"\n[GEO] Nearby farm anomaly rate: {local_anom_rate*100:.1f}% "
                  f"({len(nearby)} farms within 2° radius)")

    # Yield prediction
    pred_yield = formula_yield(user_data, crop_enc)
    crop_name  = user_data['crop_type']
    crop_avg   = _base_yields.get(crop_name, 4033)
    diff_pct   = (pred_yield - crop_avg) / crop_avg * 100
    print(f"\nPredicted Yield: {pred_yield:.0f} kg/ha  "
          f"({diff_pct:+.1f}% vs {crop_name} average of {crop_avg:,} kg/ha)")
    print("=" * 55 + "\n")

# ============================================================
# 21. EXAMPLE CALL
# ============================================================
sample_input = {
    'crop_type':          'Wheat',
    'region':             'North India',
    'soil_moisture_%':    5.0,
    'soil_pH':            6.2,
    'temperature_C':      42.0,
    'rainfall_mm':        280.0,
    'humidity_%':         85.0,
    'NDVI_index':         0.18,
    'sunlight_hours':     7.5,
    'pesticide_usage_ml': 20.0,
    'total_days':         120,
    'season_sin':         0.5,
    'season_cos':         0.866,
    'latitude':           28.6,    # optional — for geo context
    'longitude':          77.2,
}
predict_user_input(sample_input)

# ============================================================
# 22. PERFORMANCE METRICS SUMMARY
# ============================================================
final_metrics = {
    'f1':        round(f1_score(df_eval['is_anomaly'],
                               df_eval['predicted_anomaly'], zero_division=0), 3),
    'precision': round(precision_score(df_eval['is_anomaly'],
                                       df_eval['predicted_anomaly'], zero_division=0), 3),
    'recall':    round(recall_score(df_eval['is_anomaly'],
                                    df_eval['predicted_anomaly'], zero_division=0), 3),
    'auc_roc':   round(roc_auc_score(df_eval['is_anomaly'],
                                      df_eval['final_score']), 3),
}
print("Final ensemble performance:", final_metrics)

# ============================================================
# 23. SAVE ALL MODELS TO BUNDLE
# ============================================================
bundle = {
    # Anomaly models
    'if_models':           if_models,
    'lof_models':          lof_models,
    'scalers':             scalers,
    'fusion_models':       fusion_models,
    # Normalisers
    'norm_if':             norm_if,
    'norm_lof':            norm_lof,
    'norm_ae':             norm_ae,
    'norm_fus':            norm_fus,
    # Ensemble
    'weights':             weights,
    'best_thresh':         best_thresh,
    'ae_thresh_raw':       ae_threshold_raw,
    # Metadata
    'encoders':            encoders,
    'segment_stats':       segment_stats,
    'features':            FEATURES,
    'performance_metrics': final_metrics,
    # Yield
    'crop_base_map':       crop_base_map,
    # [CLS] Anomaly type classifier
    'type_classifier':         type_classifier,
    'classifier_feature_names':classifier_feature_names,
    # [GEO] Clustering results
    'cluster_summary':     cluster_df,
}

with open("models/model_bundle.pkl", "wb") as f:
    pickle.dump(bundle, f)

for (crop, region), ae in autoencoders.items():
    ae.save(f"models/ae_{crop}_{region}.keras")

print("\n✅ All models saved to models/")
print("Files generated:")
print("  models/model_bundle.pkl")
for (crop, region) in autoencoders:
    print(f"  models/ae_{crop}_{region}.keras")
print("  shap_if_summary.png")
print("  ablation_full_final.png")
print("  results_summary.png")
print("  geospatial_clustering.png")
print("  anomaly_type_classification.png")
print("  shap_type_classifier.png")

# Download models zip
import shutil
from google.colab import files
shutil.make_archive('models', 'zip', 'models')
files.download('models.zip')

